apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbcheck
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dbcheck
  template:
    metadata:
      labels:
        app: dbcheck
    spec:
      containers:
      - name: dbcheck
        image: ericgregory/5min-dbcheck:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: "usr/src/app/secrets"
        env:
        - name: TOKEN_TEST
          valueFrom:
            secretKeyRef:
              name: api-token
              key: token
      volumes:
        - name: secrets
          secret:
            secretName: dbpwd
            defaultMode: 0400
