apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbcheck
  template:
    metadata:
      labels:
        app: dbcheck
    spec:
      containers:
      - name: dbcheck
        image: ericgregory/5min-dbcheck:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: "usr/src/app/secrets"
        env:
        - name: TOKEN_RAHARJA
          valueFrom:
            secretKeyRef:
              name: dbraharja
              key: password  #ENCRYPTED PASSWORD with hiden values
        - name: PASSWORD_RAHARJA
          value: "panji123"  #plain password as is, it can be read by anyone (unprotected)
      volumes:
        - name: secrets
          secret:
            secretName: dbpwd
            defaultMode: 0400
