apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    password: AgByhjkaj0lY4hef7nnYx6EtwghqG6PlC/I1ttkBYB2j7gYkRgvezbnROs7XBJLMTT6dIxafw/uuBOjcXzNBVSziwAFM+JTX7dokPzF2bsiSkCX9JzauKTWVaQpDGQXgHScWNdep9EiKQCS4+DDB0V6f/iKP01JoN51Xm1JB+ajIV7Tkg8+XwTnAVKlaN2VMjSus2nif78eah7Zt+w5aF3TKUuYcxxPDFicwf9WDe9XlctN0POSp3lcHtCY/Y9IYQvVtzCE9EPTpYkK9nAGzJlLqiMMI0ksoNBWsuS1J6kuxypEkmnrkh52JdT1+KJz5H6EFWs9CP/oB9F8wZ5QOutcvRk5UlnnDDUhqk7dftRIcUy6G5I5xGoP3kWZkhURn474d6uzz7cEyZf/m4sq3635AOju2alimmYEWcveyK9JdYeAH5r57JEgp6GmacA+ygPJScGB7GQ5ZEfjPCYumTBDOBHtbH8BhLdDkxuj1HNuYGV+nSJFvwzRbcCYo/84G2d3WAcX/hl6xjUrhlSaJcOnNvgRFinxIE48789xQiaD0qQxoXkmb1lVtkZgsfftTNbKIUptugnIcpK8H0+lVw8+PF8mzzKMJ87MD6Tp8AMUH5WMfLaL5uD3QC4NMW2tpulDFgTNCZ1LdG9Bwovl9TFZZUjACScHPRRIKW2fLYtg5YGtugwv6jzGECx7BX4rSBTL3Cxg=
    username: AgAgGCxnB4IKEY0baD158FZUC7rJDW/gLHrTZjXyYYWKdT84O9RbPhfSp06fb4POg/ry9yNQ7jd8UwpxJTK0KjSmDjTafxggiolap0COpJ+tpdcbFd6i2OIWSNGDju2fakaiZFNnvXHd6Mii9076E1Slwrq1CjL6FkpdhXZ3R9VWe1C8tSR/HVyer/O5cK1e8DQHwBgkDleUofj05JqDxHOWhYnFS5U01rbMQxbIgMwEVBX38hq79btQlEVGKSkB0/lFlKn8AF/I3y54dJhDoZjwIkH/bGwIh0Nf33SzdAK7wfdyd3QK1umAThsf7fh2Mad0h3LCphc4W8eqoczI3Fu1LzP/V8eEQryQGP99km1w/QBcd0KHGV7YPOibJXQ88gRQo8+QJ7s+ZTblaFcyPzfvo4xWMAwWWEu18ns290F6Nj6u1zUjXuizMmraPeQHTXcksTM6rMsp6xVvSKqAD1IV19V5tfq/EsY3oB1EGEDxKwK3HfTEyKsc5ZWk539YolIWT2jbWE8c3DY9dZtJ1q3l7SWYWZT6YuQyNXwasnaPxMFcQbydqqsllofqLsqoX7VaX/tbVzC68WisusKLgS20lggH74Sm78SsBbiYlY9kcUvKtAdl8PDiFBNuTa5mvehq0NcwiQiWEO0gIDgP7kBUOOC8fCES+bDxN/Amg5GWs7aAeBkcO5aoluPWOwIiwhayB+TCkw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test-secret
spec:
  encryptedData:
    password: AgAY1PXjcuZTPfIFwrpvWlqAxIyeB6uW+iudX4VZZZ58JE8AP8r4gDNhBepqo6xVqNuroQoz/PAjy5G87vair1DOBHPrShcwsknneWlloxk31zfup+ur/DCMzFw8hwMOT4vhqsbio0YvS4uONBY+qx8gls38ZvIVcpbTKkQC/O3+OPcTShchp4U77t4JK25bBcED1EILn37qjg4GToNBtDqk6XxW9MJpHuKvpFwebya7MZf2k6Oyuskh/DE1U12reJkrAdeb4yneaYyVglQrT/OUyAHr6zyPCE0x/DhyNJ6Arn0Qe3UDk2oT+asuwmC8skFCEGeM7sKMnPKY7x7u/Lxpfe6mnnHYaq2YEtW6FKErDgVxllvC8h9WrzqPCaLKGcjCTcXTpeyY4C9jSgAryWYiDra3vilkaC4Bmzsbr/Bm+U1gDIuMrEJXUqkgayXaRNbi6piDfV/lDdjTSTAoWHRrFxc1PjLgalUv4YrorlAsNY0FckKFb3IYFjMmzbBqXceyCOU69+MuSV62EtWP4CBgxtAktk68Y/vHUc6SpD8dVHL77P1/N2fkP8PnF9J4l5l4o4DkIEYGgaoWXNv6+iBn4rqPovtIW/BpNNLH7yDIvEtxMzVtfiGL68t5xmqhJko6jnHJY/oi1jFU62/4prMDwSBFgN7AArgbTPDEldkyhKbqIU0+Q63sBLSRvsLu4TnKH9hS2IA+5g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: test-secret
