apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysqlpwd
spec:
  encryptedData:
    password: AgBOa9p3PSQXjmjN7B9nbkwmRQAGE37ugi2GUDwtBELkRJbNXdrK/eLHBvKJTITwlUtZu3VjunnOEYuXLjoYUv/zA1sFW7+9HUcs9Gv4L2nXsGj3FpjRv8jYRJWzEvUUAZdGsvwIaP9jK96pRUUvrXBEgwdbPvilRRCCDEzIvjoJoHbMZegyZBQgZD2eYmGqkwWT5+JWSOwbmOW3dnpX+tW6amP/rii8SbyFDTs33G4OFdxIs63fQ96lvQVHrGBbsR7VfqIXlvKyRPPVpOz2xIFzcHlJQj18GYXVkHoUCP6pRc4SEZpIyQe+hV3exp26n1mXEThpPOwtRPLLfxbCJyJOztgexGkzdht5fsALwhSEXzQAvwMimnqiyZYyLsRE28kzVAnvxQ+YGULAUwRH7VdzfM5f2oj0ri/KCco5+RgTH3nX+oPF5t/itEW8i5iJSC/M36Ch4iJP0miUHtpP9m6BFIHOuTPPz/hkj8nzhR4cLW6TztGqpTh3VHWlqqpoULeqx6Bit73WZocZN9eB5fr9TqCAHBLH/qNd5ybjpHa5lLUldgLTaZRHJfH5O2PVYTEEoRssQ3GT/kZuxs7pXkhM+1eYfyzq6NmZZVWYprPaGP7XwPa/gKCmMUpOkXmACclb3xmASjhRvPVtOuGqeODkmRncfHtQ7mlxiF+GmjDu0hpbvXXSpzmGh8b+IMrA/XrkjhFDtik=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysqlpwd
