apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test-secret
spec:
  encryptedData:
    password: AgB87spmfeHfxutYn2Ej2NivAI1C4fesFfeXagpJlC7+pASQNdWgWtmrJuUL+QSE1Migea39gqXZBLB2HV+BrSd6oSErPPTK2xIhojf17paZmGrhQmpoL/pAIgPDesV7Kwca1GTfeJiALqshhu/UfT+qkFVe84hJDC12gtjp+9RAAS4FmakLx3j9V8RcpBHkOW/rhnVpi0A5ZxpG68uRl5FAPqb8qU2lRpwAEMXb60USnMy5MZbFfGlYOvh+r5oMnpkwgf9oSieFoXmV/ctRhf8ufuH38KhqTNRnXnDpW9jxa7I+gAg7VJsVFfKVqetW9EAVAqtNN9AfspNlN9Vy3dZjbpPM16yI/X4dNfm7Z1SSfh1eTq/5KvClJHnRh7hxOAp3v3Q/ngvMlJLmVMOJXZLEq6oA5oP2hMi74VK0pfo/biyD7Pw7H4eN7KwuQAIzkJkkJP38iROkFs/Uit5P0p7xG7jX7O6XuJnP+oTgyHZhJfq1SA7zVURx2JFMK2GBxKmBQlRQkRsPCFk5rluFSs9ULsCRlwhWlwKO6y7Ejoy9rqwAmZK8wqpbApQngC2d4WkPvRSRbY8sMDt4R8kCClbhAN8YxF1XOrHXJ4vMxjMIdbhVWB8dCfpYZTumpowiBLyWul5/Qv/w1aXl6Ppq2gTRv0qiPqdwnK6YUknr42hj1CmswTTLVWv7NZGwvmd+1ADxMbI+FDx9Kl+gMw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: test-secret
